nama                    = input("Nama                     : ")
nim                     = input("NIM                      : ")
kelas_paralel           = input("Kelas Paralel            : ")
tempat_tanggal_lahir    = input("Tempat/Tanggal Lahir     : ")
alamat                  = input("Alamat                   : ")
hobby                   = input("Hobby                    : ")
No_HP                   = input("No. HP                   : ")

print()
print("Nama                     :" + nama)
print("NIM                      :" + nim)
print("Kelas Paralel            :" + kelas_paralel)
print("Tempat/Tanggal Lahir     :" + tempat_tanggal_lahir)
print("Alamat                   :" + alamat)
print("Hobby                    :" + hobby)
print("No. HP                   :" + No_HP)