print("##############################")
print("#                            #")
print("#   Aurora Shafa Salsabila   #")
print("#      2510817220010         #")
print("#                            #")
print("##############################")